---
- name: "Creating of {{ vagrant_user }} user"
  user:
    name: "{{ vagrant_user }}"
    comment: "John Vagrant"
  become: true

- name: "Add {{ vagrant_user }} to sudoers"
  lineinfile:
    dest: "/etc/sudoers.d/{{ vagrant_user }}"
    state: present
    regexp: '^{{ vagrant_user }}'
    line: '{{ vagrant_user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
    create: yes
  become: true

- name: "Create {{ vagrant_user }} .ssh"
  file:
    path: "/home/{{ vagrant_user }}/.ssh"
    owner: "{{ vagrant_user }}"
    group: root
    state: directory
    mode: 0700
  become: true

- lineinfile:
    line:  "{{ lookup('file', vagrant_user_import_ssh_pub_key) }}"
    path:  "/home/{{ vagrant_user }}/.ssh/authorized_keys"
    create: yes
    mode: 0600
    owner: "{{ vagrant_user }}"
    state: present
  when: vagrant_user_import_ssh_pub_key | default(False)
  become: true

- name: "Check /home/{{ vagrant_user }}/.ssh/authorized_keys"
  stat:
    path: /home/{{ vagrant_user }}/.ssh/authorized_keys
  register: authorized_keys_file
  become: true

- block:
    - name: "Check /root/.ssh/authorized_keys"
      stat:
        path: /root/.ssh/authorized_keys
      register: root_authorized_keys_file

    - name: "Copy /root/.ssh/authorized_keys"
      copy:
        remote_src: true
        src:  /root/.ssh/authorized_keys
        owner: "{{ vagrant_user }}"
        mode: 0600
        dest: "/home/{{ vagrant_user }}/.ssh/authorized_keys"
      when: root_authorized_keys_file.stat.exists == True

  when: authorized_keys_file.stat.exists == False and 
        vagrant_user_import_ssh_pub_key | default(True)
  become: true

